services:
  acl:
    container_name: aclservice
    image: stjarnstoft/aclservice:dev
    build:
      context: .
      target: dev
    environment:
      GB_CONSTRING: "mongodb://acldb"
    ports:
      - "8081:8080"
      - "2345:2345"
    volumes:
      - ./:/app
  acl-db:
    container_name: acldb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: