apiVersion: apps/v1
kind: Deployment
metadata:
  name: "aclservice-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "aclservice-app"
  template:
    metadata:
      labels:
        app: "aclservice-app"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: aclservice-container
        image: ghcr.io/superellips/aclservice:eb1c8e2641bd77c28fee810681f440300c3ef91c
        resources:
          limits:
            cpu: "10"
            memory: "100Mi"
          requests:
            cpu: "10 "
            memory: "50Mi"
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: aclservice-config